-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 17:15:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forumdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forumdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forumdb` DEFAULT CHARACTER SET utf8 ;
USE `forumdb` ;

-- -----------------------------------------------------
-- Table `forumdb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(700) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NULL,
  `username` VARCHAR(50) NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` VARCHAR(255) NULL,
  `password` TEXT NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `brief` VARCHAR(500) NULL,
  `content` VARCHAR(1000) NOT NULL,
  `image` VARCHAR(255) NULL,
  `likes` INT NULL,
  `dislikes` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `status` INT(1) NULL,
  `category_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_category_idx` (`category_id` ASC),
  INDEX `fk_post_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_post_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `forumdb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `forumdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(500) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `status` INT(1) NULL,
  `likes` INT NULL,
  `dislikes` INT NULL,
  `users_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_users1_idx` (`users_id` ASC),
  INDEX `fk_comment_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comment_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `forumdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `forumdb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `like` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_like_users1_idx` (`users_id` ASC),
  INDEX `fk_like_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_like_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `forumdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `forumdb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`likescmt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`likescmt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `like` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `comment_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likescmt_comment1_idx` (`comment_id` ASC),
  INDEX `fk_likescmt_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_likescmt_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `forumdb`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likescmt_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `forumdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`, `post_id`),
  INDEX `fk_favorite_users1_idx` (`users_id` ASC),
  INDEX `fk_favorite_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_favorite_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `forumdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `forumdb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
